spring:
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.debug: true
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.gersondeveloper.cadastroavd2024: DEBUG
    root: INFO
    org.springframework.boot.autoconfigure.liquibase: DEBUG
    org.liquibase: DEBUG